### ISSUE TITLE
Last functional release

### ISSUE THREAD

**Issue by ghost** [iontorrent/TMAP#2]
Dear developers,

The most recent commit does not compile on none of my systems (centos & debian various versions).
I don't know much about C/C++, so I don't know what's missing here.
I receive the following error message during compilation:

if g++ -DHAVE_CONFIG_H -I. -I. -I.     -Wall -g -O3 -pthread -msse3  -MT src/sw/lib/Solution4.o -MD -MP -MF "$depbase.Tpo" -c -o src/sw/lib/Solution4.o src/sw/lib/Solution4.cpp; \
    then mv -f "$depbase.Tpo" "$depbase.Po"; else rm -f "$depbase.Tpo"; exit 1; fi
src/sw/lib/Solution4.cpp: In member function ‘void Solution4::updateResult(int, int)’:
src/sw/lib/Solution4.cpp:253: error: ‘INT64_MAX’ was not declared in this scope

Best regards.
Tim Scheurenbrand

**Comment by nh13** [comment]
Could you post your configure script?  I have compiled the latest TMAP successfully on centos/ubuntu/macosx.

I don't have a box where the compilation fails, but I have a possible fix to try to force the "INT64_MAX" macro to be defined.  Could you checkout the following commit: 7fc8aa8b3c55fd5d806fe5d769ba6dd3b67daa4f ?

**Comment by ghost** [comment]
Trying the commit 7fc8aa8 , I get the following error during compilation:

```
if g++ -DHAVE_CONFIG_H -I. -I. -I.     -Wall -g -O3 -pthread -msse3 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -MT src/sw/lib/Solution4.o -MD -MP -MF "$depbase.Tpo" -c -o src/sw/lib/Solution4.o src/sw/lib/Solution4.cpp; \
then mv -f "$depbase.Tpo" "$depbase.Po"; else rm -f "$depbase.Tpo"; exit 1; fi
src/sw/lib/Solution4.cpp: In member function `int Solution4::processFastVariantA8Bit(const std::string&, int, int, int, int) [with int qec = 1]':
src/sw/lib/Solution4.cpp:246: sorry, unimplemented: inlining failed in call to 'void Solution4::updateResult(int, int) [with T = uint8_t, bool BYTE =  true]': function not inlinable
src/sw/lib/Solution4.cpp:747: sorry, unimplemented: called from here
src/sw/lib/Solution4.cpp:246: sorry, unimplemented: inlining failed in call to 'void Solution4::updateResult(int, int) [with T = uint8_t, bool BYTE =  true]': function not inlinable
src/sw/lib/Solution4.cpp:848: sorry, unimplemented: called from here
src/sw/lib/Solution4.cpp:286: sorry, unimplemented: inlining failed in call to 'void Solution4::updateResultLast() [with T = uint8_t, int DEFAULT_VALUE = 0]': function not inlinable
src/sw/lib/Solution4.cpp:882: sorry, unimplemented: called from here
```

**Comment by nh13** [comment]
What version of g++ are you using?  Could you please post the output of your configure script?

**Comment by nh13** [comment]
Could you try this patch: https://gist.github.com/2421597

**Comment by ghost** [comment]
I'll send you my configure script by mail.

```
g++ --version
g++ (GCC) 3.4.6 20060404 (Red Hat 3.4.6-10)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nh13** [comment]
Looks like you have an old version of g++ (March 2006).  Could you try upgrading your gcc/g++?

**Comment by ghost** [comment]
There's no possibility for me to update the cluster, I want to run the software on. But I understand, that it's my problem to have an up to date g++ and c-library. Thank You anyway for your quick troubleshooting.

**Comment by nh13** [comment]
Did you try the patch?

**Comment by ghost** [comment]
The patch enabled me to compile 7fc8aa8 . I'll give it a try tomorrow. Thank's a lot for your help.

**Comment by ghost** [comment]
Up to now, it seems to work. I'll tell you when the first jobs finished successfully.

**Comment by ghost** [comment]
Done. All jobs finished successfully during the weekend. Thank's a lot.
