### ISSUE TITLE
rpl_malloc problem

### ISSUE THREAD

**Issue by lmanchon** [iontorrent/TMAP#5]
--Hi 

i try to compile TMAP from github sources with:

./configure --prefix=/home/manchonl/TMAP --enable-perftools --enable-intel64

then make, and i obtain this error:

tmap_definitions.c:418: undefined reference to `rpl_malloc'

i don't find what is the problem and how to fix it.

somebody help ?

thanx

**Comment by shahm3** [comment]
If you remove "--enable-perftools" from the command and try to recompile it should work.

**Comment by lmanchon** [comment]
yes of course.

in another way i have fixed this issue keeping --enable-perftools in configure:

before configure just type: export ac_cv_func_malloc_0_nonnull=yes
then run
 ./configure --prefix=/home/me/TMAP --enable-perftools --enable-intel64

then comment these lines in configure.ac:

AC_FUNC_MALLOC
AC_FUNC_REALLOC

and then: make && make install.

hope this help.

**Comment by nh13** [comment]
Most likely the compilation cannot find the google performance tools installation.  Take a look at the configure log, or post it here.

**Comment by lmanchon** [comment]
i think not because i have set the path to find google performance tools with
export LDFLAGS="-L/home/me/google-perftools/lib" and then run configure.
