### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by BernardoBello** [iontorrent/TMAP#7]
Hi,  I have this error when typing make:

Thank you, Bernardo

usuario@bernardo:~/Desktop/TMAP-master$ make
make  all-recursive
make[1]: Entering directory `/home/usuario/Desktop/TMAP-master'
Making all in .
make[2]: Entering directory`/home/usuario/Desktop/TMAP-master'
depbase=`echo src/util/tmap_alloc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I.     -Wall -g -O3 -pthread -msse3 -D_TMAP_BWT_RUN_TYPE=0 -D_USE_KNETFILE -Isrc/samtools -DSAMTOOLS_MAIN -MT src/util/tmap_alloc.o -MD -MP -MF $depbase.Tpo -c -o src/util/tmap_alloc.o src/util/tmap_alloc.c &&\
    mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/util/tmap_definitions.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I.     -Wall -g -O3 -pthread -msse3 -D_TMAP_BWT_RUN_TYPE=0 -D_USE_KNETFILE -Isrc/samtools -DSAMTOOLS_MAIN -MT src/util/tmap_definitions.o -MD -MP -MF $depbase.Tpo -c -o src/util/tmap_definitions.o src/util/tmap_definitions.c &&\
    mv -f $depbase.Tpo $depbase.Po
In file included from src/util/../seq/tmap_seq.h:8:0,
                 from src/util/tmap_definitions.c:14:
src/util/../seq/tmap_sam.h:6:29: fatal error: ../samtools/bam.h: No such file or directory
compilation terminated.
make[2]: **\* [src/util/tmap_definitions.o] Error 1
make[2]: Leaving directory `/home/usuario/Desktop/TMAP-master'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/usuario/Desktop/TMAP-master'
make: **\* [all] Error 2
usuario@bernardo:~/Desktop/TMAP-master$

**Comment by shahm3** [comment]
Did you run "git submodule init" before running make?

**Comment by BernardoBello** [comment]
No, since "git clone" is not working for me (left if in shell but nothing happened).

I downloaded "TMAP-tmap.3.4.0.tar.gz", extracted, cd TMAP-tmap.3.4.0, and executed:

> sh autogen.sh && ./configure && make

There I had the issue.

Bernardo

**Comment by BernardoBello** [comment]
Hi,

Trying:

> git clone https://github.com/iontorrent/TMAP.git

instead of:

> git clone git://github.com/iontorrent/TMAP.git

seems TMAP was installed OK.

Thank you,

Bernardo
