### ISSUE TITLE
RG (read group) error

### ISSUE THREAD

**Issue by BernardoBello** [iontorrent/TMAP#8]
Hi,

I'm having this error. I don't know how to use the read group -R function. These are examples of my reads. I put also the shell error:

Thank you

@DX0VP:00005:00045
CCTCTATCATCCTTTATGATAGAAATATATACGTCAGAATTTAATTTGGTGAATTAAAAAGTCACCGGATTCAGCGACACTCATGGTGATTTCTCACTGATAACCTTATTTTTGACGAGGGGAATTAATAGGTTG
+
A><:9?>9999299044944>@@@99998=>>>8893848</844;7;=8882424444+44444242449;=/////////444244//8+/1////444656,/,//888/119?;:::08,/,/,//,*,04
@DX0VP:00006:00039
GCGAGCAACAAGTTGCACAAAGTCTTTTCCCTGTTGGTGATATTGAAAAACCGATTGTCCGAGCTATTGCAGAAGACCTAGGTTAGCGAACAGTTGGGGCGATGTGAATGAAGCTCGTCAAGAGATCTTAGAGTCTTCGAACGTGCGAAAAATAATTAAA
+
69@849C===>@@;>>>>>A1499999/9>59AB?G@BBB?@@<99999,98844<;9@=@@@@@>>49998><><<7700,/,.27,11/866,0..*49>>>>8858>><899>>>@A=ACAA@9969?>>>99599A?999==99999,9969511,
@DX0VP:00007:00043
AGCGCGTAAAATAATTTTTAACTTTTCAAAACTCCATAGCAACTCAATGACCCTGAAAGAGCGTGCTAATCCAGACATTATCAAAGGTTCACGC
+
19@9<;ABA>29959999-9<9999/49992===;9>@9995449=86<111+//88+///4444449599244:>CC?A<///,1,1:;11//
@DX0VP:00008:00044
TGAGCGTGGTAATCCGTTCCCAAACACATTCCGTCGTAAACATTAAGCATATTGGTATTCTTGGAGCCGATATGCTTACGACTGAATGTATGGTGACAGACCTACCAAAGAAGAAAAGCTGACCTAGGCGTGGAATGGCGGTATGGGTGGAATGGGCGGAATAGTTCAAATACCGTATCGAAACTTAACCTTTGGTAGCG
+
###### 
###### 

usuario@bernardo:~$ tmap mapall -f /home/usuario/Documents/2013_04_18_____2/trinity_out_dir/Trinity.fasta -r /home/usuario/Documents/2013_04_18_____2/fastx_trimmer_filtered_data.fastq -i fastq -s /home/usuario/Documents/2013_04_18_____2/2013_04_18_____2.1.sam -R @DX0VP: --verbose stage1 --stage-keep-all map1
[tmap mapall] running with 8 threads (autodetected).
[tmap mapall] map1 will be run in stage 1.
[tmap mapall] reading in reference data.
[tmap mapall] 0.12/0.12 sec: reference data read in.
[tmap mapall] calculating maximum differences in map1 for stage 1.
[tmap mapall] 17bp reads will have at most 2 differences.
[tmap mapall] 38bp reads will have at most 3 differences.
[tmap mapall] 64bp reads will have at most 4 differences.
[tmap mapall] 93bp reads will have at most 5 differences.
[tmap mapall] 124bp reads will have at most 6 differences.
[tmap mapall] 157bp reads will have at most 7 differences.
[tmap mapall] 190bp reads will have at most 8 differences.
[tmap mapall] 225bp reads will have at most 9 differences.

src/io/tmap_seqs_io.c:248: in function "tmap_seqs_io_to_bam_header"
Read group improperly formatted (no colon)
fatal error: the value is out of range

**Comment by shahm3** [comment]
The –R parameter doesn't like the format you have given mainly colon, try a different string. Also, I think tmap will run even if you don't specify –R, it assign it a default value.
